ecommerce/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'ecommerce' # This will be like this: {% url 'ecommerce:detail' item.id %} on our templates. 
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^products/$', views.products, name='products'),
	url(r'^product/(?P<product_id>[0-9]+)/$', views.single_product, name='single_product'),
	url(r'^about/$', views.about, name='about'),
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^cart/$', views.cart, name='cart'),
	url(r'^checkout/$', views.checkout, name='checkout'),
	
	url(r'^user/', include([
        url(r'^login/$', views.user_login, name='user_login'),
		url(r'^register/$', views.user_register, name='user_register'),
		url(r'^account/$', views.user_account, name='user_account'),
		url(r'^products/$', views.user_products, name='user_products'),
		url(r'^product/create/$', views.user_product_create, name='user_product_create'),
		url(r'^product/update/(?P<product_id>[0-9]+)/$', views.user_product_update, name='user_product_update'),
		url(r'^product/update/set-featured-image/$', views.set_featured_image),
		url(r'^product/update/unset-image/$', views.unset_image),
		url(r'^product/unset-product/$', views.unset_product),
		url(r'^logout/$', views.logout),
    ])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'ecommerce/', include('ecommerce.urls')), # Include ecommerce app views. 
    url(r'^admin/', admin.site.urls),
]

ecommerce/models.py
from django.db import models
from django.contrib.auth.models import User

class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=30)
    about = models.TextField()
    
class Product(models.Model):
    name = models.CharField(max_length=200)
    content = models.TextField()
    excerpt = models.TextField()
    price = models.DecimalField(max_digits=20, decimal_places=2)
    status = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    quantity = models.PositiveIntegerField()
    author = models.PositiveIntegerField()
    featured_image = models.CharField(max_length=300)

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField()

ecommerce/forms.py
from django import forms

class RegisterForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
	password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False)
	
class AccountForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False)
	about_me = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}), required=False)
	
class CreateProductForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}))
	excerpt = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows': '7'}), required=False)
	price = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Amount'}))
	status = forms.CharField(widget=forms.Select(choices=(('1', 'Active'),('0', 'Inactive'),), attrs={'class':'form-control'}))
	quantity = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))
	
class UpdateProductForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}))
	excerpt = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows': '7'}), required=False)
	images = forms.CharField(widget=forms.FileInput(attrs={'class':'form-control image-input', 'accept': 'image/*', 'multiple': 'multiple'}), required=False)
	price = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Amount'}))
	status = forms.CharField(widget=forms.Select(choices=(('1', 'Active'),('0', 'Inactive'),), attrs={'class':'form-control'}))
	quantity = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))

ecommerce/views.py
import os
import re

from django.contrib.auth import authenticate, login, logout as django_logout # Use alias like "django_logout" so that django doesnt get confused on which function to use.
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import intcomma
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.template.defaulttags import register
from .apps import EcommerceConfig
from .models import Member, Product, Image, User
from .forms import *
from .helpers import Helpers
from time import gmtime, strftime

def index(request):
	preview_products = Product.objects.all().order_by('-id')[:12]
	
	return render(request, Helpers.get_url('index.html'), {'products': preview_products, 'currency': EcommerceConfig.currency})

def single_product(request, product_id):
	product = get_object_or_404(Product, pk=product_id)
	author = get_object_or_404(User, pk=product.author)
	product_images = product.image_set.all()
	images = []
	cart_items = request.session
	
	# Create an empty cart object if it does not exist yet 
	if not cart_items.has_key("cart"):
		cart_items["cart"] = {}
		
	in_cart = True if cart_items['cart'].get(str(product_id)) else False
	
	if product_images:
		for data in product_images:
			images.append({"small": Helpers.get_path(str(data.image)), 'big': Helpers.get_path(str(data.image))})
	
	return render(request, Helpers.get_url('product/single.html'), {'product': product, 'images': str(images).replace("'", '"'), 'in_cart': in_cart, 'author': author, 'currency': EcommerceConfig.currency})
	
def products(request):
	if request.method == 'POST':
		pagination_content = ""
		page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
		page = int(page_number)
		name = request.POST['data[name]']
		sort = '-' if request.POST['data[sort]'] == 'DESC' else ''
		search = request.POST['data[search]']
		max = int(request.POST['data[max]'])
		
		cur_page = page
		page -= 1
		per_page = max # Set the number of results to display
		start = page * per_page
		
		# If search keyword is not empty, we include a query for searching 
		# the "content" or "name" fields in the database for any matched strings.
		if search:		 
			all_posts = Product.objects.filter(Q(content__contains = search) | Q(name__contains = search)).exclude(status = 0).order_by(sort + name)[start:per_page]
			count = Product.objects.filter(Q(content__contains = search) | Q(name__contains = search)).exclude(status = 0).count()
			
		else:
			all_posts = Product.objects.exclude(status = 0).order_by(sort + name)[start:cur_page * max]
			count = Product.objects.exclude(status = 0).count()
		
		if all_posts:
			cart_items = request.session
			
			# Create an empty cart object if it does not exist yet 
			if not cart_items.has_key("cart"):
				cart_items["cart"] = {}
			
			for post in all_posts:
				in_cart = True if cart_items['cart'].get(str(post.id)) else False
				action = 'delete' if in_cart else 'add'
				status = 0 if in_cart else 1
				
				if in_cart:
					button = "<input type='submit' value='Remove from Cart' class='btn btn-block btn-danger' />"
				else:
					button = '''
						<div class='input-group'>
							<div class="input-group mb-2">
								<div class="input-group-prepend">
									<div class="input-group-text">Qty</div>
								</div>
								<input type='number' id='quantity' min='1' max='%d' class='form-control' name='quantity' value='1' />
								<div class="input-group-append">
									<button type='submit' class='btn btn-primary'>Add To Cart</button>
								</div>
							</div>
						</div>
					''' %(post.quantity)
				
				pagination_content += '''
					<div class='col-md-3 col-sm-6'>
						<div class='card mb-2'>
							<div class='card-header'>%s</div>
							<div class='card-body p-0'>
								<a href='%s'>
									<img src='%s' width='%s' class='img-responsive'>
								</a>
								<div class='list-group list-group-flush'>
									<div class='list-group-item border-top-0 py-2'>
										<i class='fa fa-shopping-cart fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>Price</p>
										<h4 class='list-group-item-heading'>%s %s</h4>
									</div>
									<div class='list-group-item py-2'>
										<i class='fa fa-cubes fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>On Stock</p>
										<h4 class='list-group-item-heading'>%d</h4>
									</div>
								</div>
							</div> 
							<div class='card-footer'>
								<form method='post' action='/ecommerce/cart/'>
									<input type='hidden' name='redirect' value='/ecommerce/products/?cart=%s&page=%s' />
									<input type='hidden' name='action' value='%s' />
                                    <input type='hidden' name='item_id' value='%d' />
									%s
                                </form>
							</div>
						</div>
					</div>
				''' %(post.name, Helpers.get_path('product/' + str(post.id)), Helpers.get_path(post.featured_image), '100%', EcommerceConfig.currency, intcomma(post.price), post.quantity, status, cur_page, action, post.id, button)
		else:
			pagination_content += "<p class='bg-danger'>No results</p>"
		
		return JsonResponse({
			'content': pagination_content, 
			'navigation': Helpers.nagivation_list(count, per_page, cur_page)
		})
	else:	
		return render(request, Helpers.get_url('product/index.html'))
	
def about(request):
	return render(request, Helpers.get_url('about.html'))
	
def contact(request):
	return render(request, Helpers.get_url('contact.html'))

def paymentDetails(request):
	return render(request, Helpers.get_url('payment-details.html'))
	
def user_login(request):
	# Redirect if already logged-in
	if request.user.is_authenticated:
		return HttpResponseRedirect(Helpers.get_path('user/account'))
	
	if request.method == 'POST':
		# Process the request if posted data are available
		username = request.POST['username']
		password = request.POST['password']
		# Check username and password combination if correct
		user = authenticate(username=username, password=password)
		if user is not None:
			# Success, now let's login the user. 
			login(request, user)
			# Then redirect to the accounts page.
			return HttpResponseRedirect(Helpers.get_path('user/account'))
		else:
			# Incorrect credentials, let's throw an error to the screen.
			return render(request, Helpers.get_url('user/login.html'), {'error_message': 'Incorrect username and / or password.'})
	else:
		# No post data availabe, let's just show the page to the user.
		return render(request, Helpers.get_url('user/login.html'))
 
def user_account(request):
	err_succ = {'status': 0, 'message': 'An unknown error occured'}
	
	# Create instance of the form and populate it with requests
	form = AccountForm(request.POST)
	
	# Redirect if not logged-in
	if request.user.is_authenticated == False:
		return HttpResponseRedirect(Helpers.get_path('user/login')) 
	
	if request.method == 'POST':
		if form.is_valid():	
			# Query data of currently logged-in user.
			user = User.objects.get(username=request.user.username)
			
			# Check if username exists
			if User.objects.filter(username=form.cleaned_data['username']).exists() and user.username != form.cleaned_data['username']:
				err_succ['message'] = 'Username aleady taken, please enter a different one.'
			
			# Check if email exists		
			elif User.objects.filter(email=form.cleaned_data['email']).exists() and user.email != form.cleaned_data['email']:
				err_succ['message'] = 'Email already taken, please enter a different one'
				
			elif form.cleaned_data['old_password'] and form.cleaned_data['password_repeat'] and form.cleaned_data['password']:
				# Check if passwords match
				if form.cleaned_data['password_repeat'] != form.cleaned_data['password']:
					err_succ['message'] = 'New password do not match.'
				
				# Check if old password is correct
				elif not user.check_password(form.cleaned_data['old_password']):
					err_succ['message'] = 'Incorrect old password.'
					
			else:
				user.username = form.cleaned_data['username']
				user.first_name = form.cleaned_data['first_name']
				user.last_name = form.cleaned_data['last_name']
				
				user.member.phone_number = form.cleaned_data['phone_number']
				user.member.about = form.cleaned_data['about_me']
				
				# Save new password if passes above validations
				if form.cleaned_data['password']:
					user.set_password(form.cleaned_data['password'])
				
				# Save posted fields to their respective tables
				user.member.save()
				user.save()
				
				# Show success message
				err_succ['status'] = 1
				err_succ['message'] = 'Account successfully updated.'
			
		return JsonResponse(err_succ)
	else:
		# Let's define intial data that we are going to use to populate our account form.
		user_data = {
			'username': request.user.username, 
			'email': request.user.email, 
			'first_name': request.user.first_name, 
			'last_name': request.user.last_name, 
			'phone_number': request.user.member.phone_number, 
			'about_me': request.user.member.about 
		}
		# Render the account form
		return render(request, Helpers.get_url('user/account.html'), {'form': AccountForm(initial=user_data)})

def user_products(request):
	# Redirect if not logged-in
	if request.user.is_authenticated == False:
		return HttpResponseRedirect(Helpers.get_path('user/login'))
	
	if request.method == 'POST':
		pagination_content = ""
		page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
		page = int(page_number)
		name = request.POST['data[th_name]']
		sort = '-' if request.POST['data[th_sort]'] == 'DESC' else ''
		search = request.POST['data[search]']
		max = int(request.POST['data[max]'])
		

ecommerce/templates/ecommerce/product/create.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container">
		<p>
			<a href = "/ecommerce/user/products" class="font-weight-bold"><span class="glyphicon glyphicon-chevron-left"></span> 
				<i class="fas fa-arrow-left"></i> &nbsp; <u>All products</u>
			</a>
		</p>
		
		<form method="post" action="{% url 'ecommerce:user_product_create' %}" class="row create-product">
			{% csrf_token %}
			<div class="col-md-8">
				<div class="form-group">
					<label for="{{ form.name.id_for_label }}">Name*</label>
					{{ form.name }}
				</div>
				<div class="form-group">
					<label for="{{ form.content.id_for_label }}">Description</label>
					{{ form.content }}
				</div>
				<div class="form-group">
					<label for="{{ form.excerpt.id_for_label }}">Short Description</label>
					{{ form.excerpt }}
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="{{ form.price.id_for_label }}">Price*</label>
					<div class="input-group">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon1"><i class="fas fa-dollar-sign"></i></span>
						</div>
						{{ form.price }}
					</div>
				</div>
				<div class="form-group">
					<label for="{{ form.status.id_for_label }}">Status</label>
					{{ form.status }}
				</div>
				<div class="form-group">
					<label for="{{ form.quantity.id_for_label }}">Quantity*</label>
					{{ form.quantity }}
				</div>
				<input type="submit" class="btn btn-primary" value="Submit" />
			</div>
		</form>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/index.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container-fluid">
		{% csrf_token %}
		<form class = "post-list">
			<input type = "hidden" value = "" />
		</form>
		
		<div class="row">
			<div class="col-md-3">
				<div class="card">
					<div class="card-header">Filter</div>
					<div class="card-body">
						<div class="form-group">
							<label>Search Keyword: </label>
							<input type="text" class="form-control post_search_text" placeholder="Enter a keyword" />
						</div>
						<div class="form-group">
							<label>Per Page: </label>
							<select class="form-control post_max">
								<option value="4">4</option>
								<option value="8" selected>8</option>
								<option value="16">16</option>
							</select>
						</div>
						<div class="form-group">
							<label>Order By: </label>
							<select class="form-control post_name">
								<option value="name">Product Name</option>
								<option value="price">Price</option>
								<option value="quantity">Availabe Stocks</option>
							</select>
						</div>
						<div class="form-group">
							<label>Sorting: </label>
							<select class="form-control post_sort">
								<option value="ASC">Ascending</option>
								<option value="DESC">Descending</option>
							</select>
						</div>
						<input type = "submit" value = "Filter" class = "btn btn-primary btn-block post_search_submit" />
						
					</div>
				</div>
			</div>
			
			<div class="col-md-9">
				{% if request.GET.cart %}
					<div class="alert alert-success">
						{% if request.GET.cart == '0' %}
							Item successfully removed from cart
						{% else %}
							Item successfully added to cart
						{% endif %}
					</div>
				{% endif %}
				<div class="products-view-all">
					<div class="pagination-container row"></div>
					<div class="pagination-nav"></div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/single.html
{% extends "ecommerce/base.html" %}
{% load humanize %}

{% block content %}		
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				{% if request.GET.cart %}
					<div class="alert alert-success alert-dismissable">
						{% if request.GET.cart == '0' %}
							Item successfully removed from cart
						{% else %}
							Item successfully added to cart
						{% endif %}
					</div>
				{% endif %}
			</div>
			
			<div class="col-md-8">
				<h3 class="mb-3">{{ product.name }}</h3>
				
				<input type = "hidden" class = "item-images-json" value = '{{ images }}' />
				<div class = "imageviewer">
					<div class = "image-container"></div>
					<i class="fas fa-arrow-circle-left prev"></i>
					<i class="fas fa-arrow-circle-right next"></i>
					
					<div class = "footer-info">
						<span class = "current"></span>/<span class="total"></span>
					</div>
				</div>
				
				<div class="card">
					<div class="card-header">Details</div>
					<div class="card-body">
						{{ product.content|safe }}
					</div>
				</div>
			</div>
			
			<div class="col-md-4">
				<div class="card">
					<div class="card-header">
						Details
					</div>
					<div class="card-body">
						<h2 class="text-danger">{{ currency }} {{ product.price|intcomma }}</h2>
						
						<p>{{ product.excerpt|linebreaks }}</p>
						
						<hr />
						
						<p><strong>Date Posted</strong>: {{ product.date }}</p>
						<p><strong>On Stock</strong>: {{ product.quantity }}</p>
						
						<hr />
						<form method="post" action="{% url 'ecommerce:cart' %}">
							{% if in_cart %}
								<input type="submit" value="Remove from Cart" class="btn btn-block btn-danger" />
							{% else %}
								<div class="input-group">
									<div class="input-group-prepend">
										<div class="input-group-text">Qty</div>
									</div>
									<input type="number" id="quantity" min="1" max="{{ product.quantity }}" class="form-control" name="quantity" value="1" />
									<div class="input-group-append">
										<button type="submit" class="btn btn-primary">Add To Cart</button>
									</div>
								</div>
							{% endif %}
							<input type="hidden" name="redirect" value="{% url 'ecommerce:single_product' product.id %}?cart={{ in_cart|yesno:'0,1' }}" />
							<input type="hidden" name="action" value="{{ in_cart|yesno:'delete,add' }}" />
							<input type="hidden" name="item_id" value="{{ product.id }}" />
					</div>
				</div>
				
				<div class="card">
					<div class="card-header">
						Seller
					</div>
					<div class="card-body">
						<p>
							<h3>{{ author.first_name }} {{ author.last_name }} </h3>
							<strong>Email:</strong> <a href="mailto:{{ author.email }}">{{ author.email }}</a><br />
							<strong>Phone:</strong> <a href="tel:{{ author.member.phone_number }}">{{ author.member.phone_number }}</a>
						</p>
						
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/update.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container item-edit" id="item-{{ product.id }}">
		<p>
			<u><a href = "{% url 'ecommerce:user_products' %}" class="font-weight-bold">My Products</a></u>&nbsp; |&nbsp;
			<u><a href = "{% url 'ecommerce:single_product' product.id %}" target="_blank" class="font-weight-bold">View Product</a></u>
		</p>
		
		<div class="wave-box-wrapper">
			<div class="wave-box"></div>
			<form action="{% url 'ecommerce:user_product_update' product.id %}" method="post" enctype="multipart/form-data" class="row update-product" >
				{% csrf_token %}
				<div class="col-md-8">
					<div class="form-group">
						<label for="{{ form.name.id_for_label }}">Name</label>
						{{ form.name }}
					</div>
					<div class="form-group">
						<label for="{{ form.content.id_for_label }}">Description</label>
						{{ form.content }}
					</div>
					<div class="form-group">
						<label for="{{ form.excerpt.id_for_label }}">Short Description</label>
						{{ form.excerpt }}
					</div>
					<div class="form-group">
						<label for="{{ form.images.id_for_label }}">Upload Images</label>
						{{ form.images }}
						<hr />
						
						<div class="images-section row">
							{% if product.image_set.all %}
								{% for data in product.image_set.all %}
									<div class="col-sm-3 mb-3">
										<i class="unset-image fas fa-trash-alt text-danger mr-2 c-p" id="unset-{{ data.id }}" title="Delete image"></i>
										{% if product.featured_image == data.image %}
											<i class="set-featured-image fas fa-star c-p" title="Set as featured image" id="featured-{{ data.image }}" style="color: #E4C317"></i>
										{% else %}
											<i class="set-featured-image far fa-star c-p" title="Set as featured image" id="featured-{{ data.image }}"></i>
										{% endif %}
										<div>
											<img src = "/ecommerce/{{ data.image }}" class="img-thumbnail img-responsive" />
										</div>
									</div>
									
									{% if forloop.counter|divisibleby:4 == 1 %}
										<div class="clearfix"></div>
									{% endif %}
								{% endfor %}
							{% else %}
								<div class="alert alert-danger no-item-images w-100 mx-3">No images found</div>
							{% endif %}
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label for="{{ form.price.id_for_label }}">Price</label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text" id="basic-addon1"><i class="fas fa-dollar-sign"></i></span>
							</div>
							{{ form.price }}
						</div>
					</div>
					<div class="form-group">
						<label for="{{ form.status.id_for_label }}">Status</label>
						{{ form.status }}
					</div>
					<div class="form-group">
						<label for="{{ form.quantity.id_for_label }}">Quantity</label>
						{{ form.quantity }}
					</div>
					<input type="submit" class="btn btn-primary" value="Update" />
				</div>
			</form>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/user.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container products-view-user">
		{% csrf_token %}
		<form class = "post-list">
			<input type = "hidden" value = "" />
		</form>
		
		<div class="form-inline float-left">
			<label>Per Page:</label>
			<select class="form-control ml-sm-2 post_max">
				<option value="5">5</option>
				<option value="10" selected>10</option>
				<option value="15">15</option>
			</select>
		
			<label class="ml-sm-3 mt-3 mt-xl-0">Search Keyword:</label>
			<input type="text" class="form-control ml-sm-2 post_search_text" placeholder="Enter a keyword">
			<input type = "submit" value = "Filter" class = "btn btn-primary mt-3 mt-xl-0 post_search_submit" />
		</div>
		
		<a href="/ecommerce/user/product/create/" class="btn btn-primary mb-3 float-right">Add New</a>
		
		<br class = "clear" />
		
		<div class = "wave-box-wrapper">
			<div class = "wave-box"></div>
			<div class = "table-responsive">
				<table class = "table table-striped table-post-list">
					<thead>
						<tr>
							<th>Image</th>
							<th id = "name" class = "active"><a href = "#">Name</a></th>
							<th id = "price"><a href = "#">Price</a></th>
							<th id = "status"><a href = "#">Status</a></th>
							<th id = "date"><a href = "#">Date</a></th>
							<th id = "quantity"><a href = "#">Quantity</a></th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody class = "pagination-container"></tbody>
				</table>
			</div>
			<div class = "pagination-nav"></div>
		</div>
	</div>
{% endblock %}