ecommerce/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'ecommerce' # This will be like this: {% url 'ecommerce:detail' item.id %} on our templates. 
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^products/$', views.products, name='products'),
	url(r'^product/(?P<product_id>[0-9]+)/$', views.single_product, name='single_product'),
	url(r'^about/$', views.about, name='about'),
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^cart/$', views.cart, name='cart'),
	url(r'^checkout/$', views.checkout, name='checkout'),
	
	url(r'^user/', include([
        url(r'^login/$', views.user_login, name='user_login'),
		url(r'^register/$', views.user_register, name='user_register'),
		url(r'^account/$', views.user_account, name='user_account'),
		url(r'^products/$', views.user_products, name='user_products'),
		url(r'^product/create/$', views.user_product_create, name='user_product_create'),
		url(r'^product/update/(?P<product_id>[0-9]+)/$', views.user_product_update, name='user_product_update'),
		url(r'^product/update/set-featured-image/$', views.set_featured_image),
		url(r'^product/update/unset-image/$', views.unset_image),
		url(r'^product/unset-product/$', views.unset_product),
		url(r'^logout/$', views.logout),
    ])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'ecommerce/', include('ecommerce.urls')), # Include ecommerce app views. 
    url(r'^admin/', admin.site.urls),
]

ecommerce/models.py
from django.db import models
from django.contrib.auth.models import User

class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=30)
    about = models.TextField()
    
class Product(models.Model):
    name = models.CharField(max_length=200)
    content = models.TextField()
    excerpt = models.TextField()
    price = models.DecimalField(max_digits=20, decimal_places=2)
    status = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    quantity = models.PositiveIntegerField()
    author = models.PositiveIntegerField()
    featured_image = models.CharField(max_length=300)

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField()

ecommerce/forms.py
from django import forms

class RegisterForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
	password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False)
	
class AccountForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False)
	about_me = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}), required=False)
	
class CreateProductForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}))
	excerpt = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows': '7'}), required=False)
	price = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Amount'}))
	status = forms.CharField(widget=forms.Select(choices=(('1', 'Active'),('0', 'Inactive'),), attrs={'class':'form-control'}))
	quantity = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))
	
class UpdateProductForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}))
	excerpt = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows': '7'}), required=False)
	images = forms.CharField(widget=forms.FileInput(attrs={'class':'form-control image-input', 'accept': 'image/*', 'multiple': 'multiple'}), required=False)
	price = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Amount'}))
	status = forms.CharField(widget=forms.Select(choices=(('1', 'Active'),('0', 'Inactive'),), attrs={'class':'form-control'}))
	quantity = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))

ecommerce/views.py
import os
import re

from django.contrib.auth import authenticate, login, logout as django_logout # Use alias like "django_logout" so that django doesnt get confused on which function to use.
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import intcomma
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.template.defaulttags import register
from .apps import EcommerceConfig
from .models import Member, Product, Image, User
from .forms import *
from .helpers import Helpers
from time import gmtime, strftime

def index(request):
	preview_products = Product.objects.all().order_by('-id')[:12]
	
	return render(request, Helpers.get_url('index.html'), {'products': preview_products, 'currency': EcommerceConfig.currency})

def single_product(request, product_id):
	product = get_object_or_404(Product, pk=product_id)
	author = get_object_or_404(User, pk=product.author)
	product_images = product.image_set.all()
	images = []
	cart_items = request.session
	
	# Create an empty cart object if it does not exist yet 
	if not cart_items.has_key("cart"):
		cart_items["cart"] = {}
		
	in_cart = True if cart_items['cart'].get(str(product_id)) else False
	
	if product_images:
		for data in product_images:
			images.append({"small": Helpers.get_path(str(data.image)), 'big': Helpers.get_path(str(data.image))})
	
	return render(request, Helpers.get_url('product/single.html'), {'product': product, 'images': str(images).replace("'", '"'), 'in_cart': in_cart, 'author': author, 'currency': EcommerceConfig.currency})
	
def products(request):
	if request.method == 'POST':
		pagination_content = ""
		page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
		page = int(page_number)
		name = request.POST['data[name]']
		sort = '-' if request.POST['data[sort]'] == 'DESC' else ''
		search = request.POST['data[search]']
		max = int(request.POST['data[max]'])
		
		cur_page = page
		page -= 1
		per_page = max # Set the number of results to display
		start = page * per_page
		
		# If search keyword is not empty, we include a query for searching 
		# the "content" or "name" fields in the database for any matched strings.
		if search:		 
			all_posts = Product.objects.filter(Q(content__contains = search) | Q(name__contains = search)).exclude(status = 0).order_by(sort + name)[start:per_page]
			count = Product.objects.filter(Q(content__contains = search) | Q(name__contains = search)).exclude(status = 0).count()
			
		else:
			all_posts = Product.objects.exclude(status = 0).order_by(sort + name)[start:cur_page * max]
			count = Product.objects.exclude(status = 0).count()
		
		if all_posts:
			cart_items = request.session
			
			# Create an empty cart object if it does not exist yet 
			if not cart_items.has_key("cart"):
				cart_items["cart"] = {}
			
			for post in all_posts:
				in_cart = True if cart_items['cart'].get(str(post.id)) else False
				action = 'delete' if in_cart else 'add'
				status = 0 if in_cart else 1
				
				if in_cart:
					button = "<input type='submit' value='Remove from Cart' class='btn btn-block btn-danger' />"
				else:
					button = '''
						<div class='input-group'>
							<div class="input-group mb-2">
								<div class="input-group-prepend">
									<div class="input-group-text">Qty</div>
								</div>
								<input type='number' id='quantity' min='1' max='%d' class='form-control' name='quantity' value='1' />
								<div class="input-group-append">
									<button type='submit' class='btn btn-primary'>Add To Cart</button>
								</div>
							</div>
						</div>
					''' %(post.quantity)
				
				pagination_content += '''
					<div class='col-md-3 col-sm-6'>
						<div class='card mb-2'>
							<div class='card-header'>%s</div>
							<div class='card-body p-0'>
								<a href='%s'>
									<img src='%s' width='%s' class='img-responsive'>
								</a>
								<div class='list-group list-group-flush'>
									<div class='list-group-item border-top-0 py-2'>
										<i class='fa fa-shopping-cart fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>Price</p>
										<h4 class='list-group-item-heading'>%s %s</h4>
									</div>
									<div class='list-group-item py-2'>
										<i class='fa fa-cubes fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>On Stock</p>
										<h4 class='list-group-item-heading'>%d</h4>
									</div>
								</div>
							</div> 
							<div class='card-footer'>
								<form method='post' action='/ecommerce/cart/'>
									<input type='hidden' name='redirect' value='/ecommerce/products/?cart=%s&page=%s' />
									<input type='hidden' name='action' value='%s' />
                                    <input type='hidden' name='item_id' value='%d' />
									%s
                                </form>
							</div>
						</div>
					</div>
				''' %(post.name, Helpers.get_path('product/' + str(post.id)), Helpers.get_path(post.featured_image), '100%', EcommerceConfig.currency, intcomma(post.price), post.quantity, status, cur_page, action, post.id, button)
		else:
			pagination_content += "<p class='bg-danger'>No results</p>"
		
		return JsonResponse({
			'content': pagination_content, 
			'navigation': Helpers.nagivation_list(count, per_page, cur_page)
		})
	else:	
		return render(request, Helpers.get_url('product/index.html'))
	
def about(request):
	return render(request, Helpers.get_url('about.html'))
	
def contact(request):
	return render(request, Helpers.get_url('contact.html'))

def paymentDetails(request):
	return render(request, Helpers.get_url('payment-details.html'))
	
def user_login(request):
	# Redirect if already logged-in
	if request.user.is_authenticated:
		return HttpResponseRedirect(Helpers.get_path('user/account'))
	
	if request.method == 'POST':
		# Process the request if posted data are available
		username = request.POST['username']
		password = request.POST['password']
		# Check username and password combination if correct
		user = authenticate(username=username, password=password)
		if user is not None:
			# Success, now let's login the user. 
			login(request, user)
			# Then redirect to the accounts page.
			return HttpResponseRedirect(Helpers.get_path('user/account'))
		else:
			# Incorrect credentials, let's throw an error to the screen.
			return render(request, Helpers.get_url('user/login.html'), {'error_message': 'Incorrect username and / or password.'})
	else:
		# No post data availabe, let's just show the page to the user.
		return render(request, Helpers.get_url('user/login.html'))
 
def user_account(request):
	err_succ = {'status': 0, 'message': 'An unknown error occured'}
	
	# Create instance of the form and populate it with requests
	form = AccountForm(request.POST)
	
	# Redirect if not logged-in
	if request.user.is_authenticated == False:
		return HttpResponseRedirect(Helpers.get_path('user/login')) 
	
	if request.method == 'POST':
		if form.is_valid():	
			# Query data of currently logged-in user.
			user = User.objects.get(username=request.user.username)
			
			# Check if username exists
			if User.objects.filter(username=form.cleaned_data['username']).exists() and user.username != form.cleaned_data['username']:
				err_succ['message'] = 'Username aleady taken, please enter a different one.'
			
			# Check if email exists		
			elif User.objects.filter(email=form.cleaned_data['email']).exists() and user.email != form.cleaned_data['email']:
				err_succ['message'] = 'Email already taken, please enter a different one'
				
			elif form.cleaned_data['old_password'] and form.cleaned_data['password_repeat'] and form.cleaned_data['password']:
				# Check if passwords match
				if form.cleaned_data['password_repeat'] != form.cleaned_data['password']:
					err_succ['message'] = 'New password do not match.'
				
				# Check if old password is correct
				elif not user.check_password(form.cleaned_data['old_password']):
					err_succ['message'] = 'Incorrect old password.'
					
			else:
				user.username = form.cleaned_data['username']
				user.first_name = form.cleaned_data['first_name']
				user.last_name = form.cleaned_data['last_name']
				
				user.member.phone_number = form.cleaned_data['phone_number']
				user.member.about = form.cleaned_data['about_me']
				
				# Save new password if passes above validations
				if form.cleaned_data['password']:
					user.set_password(form.cleaned_data['password'])
				
				# Save posted fields to their respective tables
				user.member.save()
				user.save()
				
				# Show success message
				err_succ['status'] = 1
				err_succ['message'] = 'Account successfully updated.'
			
		return JsonResponse(err_succ)
	else:
		# Let's define intial data that we are going to use to populate our account form.
		user_data = {
			'username': request.user.username, 
			'email': request.user.email, 
			'first_name': request.user.first_name, 
			'last_name': request.user.last_name, 
			'phone_number': request.user.member.phone_number, 
			'about_me': request.user.member.about 
		}
		# Render the account form
		return render(request, Helpers.get_url('user/account.html'), {'form': AccountForm(initial=user_data)})

def user_products(request):
	# Redirect if not logged-in
	if request.user.is_authenticated == False:
		return HttpResponseRedirect(Helpers.get_path('user/login'))
	
	if request.method == 'POST':
		pagination_content = ""
		page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
		page = int(page_number)
		name = request.POST['data[th_name]']
		sort = '-' if request.POST['data[th_sort]'] == 'DESC' else ''
		search = request.POST['data[search]']
		max = int(request.POST['data[max]'])
		

ecommerce/templates/ecommerce/cart.html
{% extends "ecommerce/base.html" %}
{% load humanize %}

{% block content %}
	<div class="container">
		<h2>Cart</h2>
		<br />
		
		{% if request.GET.cart %}
			<div class="alert alert-success alert-dismissable">
				{% if request.GET.cart == '0' %}
					Item successfully removed from cart
				{% else %}
					Cart item successfully updated
				{% endif %}
			</div>
		{% endif %}
		
		{% if cart_db_items %}
			<div class="table-responsive">
				<table class="table table-bordered">
					<tr>
						<th>Item</th>
						<th>Quantity</th>
						<th>Total</th>
						<th>Date Added</th>
						<th>#</th>
					</tr>
					
					{% for item in cart_db_items %}
						{% with cart_session_items|get_cart_item:item.id as cart %}  
						<tr>
							<td>
								<a href="{% url 'ecommerce:single_product' item.id %}">
									<img src="/ecommerce/{{ item.featured_image }}" class="img-responsive img-thumbnail float-left mr-2" width="50">
									{{ item.name }}
								</a>
							</td>
							<td>
								<form method="post" action="{% url 'ecommerce:cart' %}" class="form-inline">
									<input type="hidden" name="redirect" value="{% url 'ecommerce:cart' %}?cart=1" />
									<input type="hidden" name="action" value="edit" />
									<input type="hidden" name="item_id" value="{{ item.id }}" />
									<input type="number" name="quantity" style="width: 70px;" class="form-control" min="1" max="{{ item.quantity }}" value="{{ cart.quantity }}" />
									<button type="submit" class="btn btn-link"><span class="glyphicon glyphicon-floppy-save"></span> Update</button>
								</form>
							</td>
							<td>{{ currency }} {% multiply cart.quantity item.price %}</td>
							<td>{{ cart.date_added }}</td>
							<td>
								<form method="post" action="{% url 'ecommerce:cart' %}">
									<input type="hidden" name="redirect" value="{% url 'ecommerce:cart' %}?cart=0" />
									<input type="hidden" name="action" value="delete" />
									<input type="hidden" name="item_id" value="{{ item.id }}" />
									<button type="submit" class="btn btn-link"><span class="glyphicon glyphicon-trash"></span> Remove</button>
								</form>
							</td>
						</tr>
						{% endwith %}
					{% endfor %}
				</table>
			</div>
			
			<div class="row">
				<div class="col-sm-6"></div>
				<div class="col-sm-6">
					<h3>Cart totals</h3>
					<table class="table table-bordered">
						<tr>
							<th>Subtotal</th>
							<td>{{ currency }} {{ cart_total|intcomma }}</td>
						</tr>
						<tr>
							<th>Total</th>
							<td>{{ currency }} {{ cart_total|intcomma }}</td>
						</tr>
					</table>
					
					<a href="{% url 'ecommerce:checkout' %}" class="btn btn-block btn-lg btn-primary">Proceed To Checkout</a>
				</div>
			</div>
		{% else %}
			<div class="alert alert-danger alert-dismissable">Your cart is currently empty</div>
		{% endif %}
	</div>
{% endblock %}

ecommerce/templates/ecommerce/contact.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<h2>Contact Us</h2>
				<br />
				<table class="table">
					<tr>	
						<th><i class="fa fa-home fa-1x"></i> Address:</th>               
						<td>Baguio City, Philippines 2600</td>
					</tr>
					<tr>
						<th><i class="fa fa-envelope fa-1x"></i> E-Mail Address:</th>
						<td><a href="mailto:carl.fontanos@gmail.com">carl.fontanos@gmail.com</a></td>
					</tr>
					<tr>
						<th><i class="fa fa-user fa-1x"></i> Author:</th>
						<td>Carl Victor C. Fontanos</td>
					</tr>
					<tr>
						<th><i class="fa fa-link fa-1x"></i> Website:</th>
						<td><a href="http://www.carlofontanos.com">www.carlofontanos.com</a></td>
					</tr>
				</table>
				<br >
				
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3827.4021417487606!2d120.59976289999999!3d16.4043903!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3391a141aa154c0f%3A0x36133249722cd8fa!2sBaguio+Convention+Center!5e0!3m2!1sen!2sph!4v1530511139735" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>
	</div>
       

{% endblock %}

ecommerce/templates/ecommerce/index.html
{% extends "ecommerce/base.html" %}
{% load humanize static %}

{% block content %}
	
	<div id="home-carousel" class="carousel slide" data-ride="carousel" style="margin-top: -15px;">
		<ol class="carousel-indicators">
			<li data-target="#home-carousel" data-slide-to="0" class="active"></li>
			<li data-target="#home-carousel" data-slide-to="1"></li>
		</ol>
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img src="{% static 'ecommerce/img/womens_banner.jpg' %}" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="{% static 'ecommerce/img/mens_banner.jpg' %}" class="d-block w-100" alt="...">
			</div>
		</div>
		<a class="carousel-control-prev" href="#home-carousel" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#home-carousel" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	
	<div class="py-5">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-4">
					<h3><i class="fa fa-check-circle"></i> Bootstrap 4 Built</h3>
					<p>The 'Modern Business' website template by <a href="http://startbootstrap.com">Start Bootstrap</a> is built with <a href="http://getbootstrap.com">Bootstrap 3</a>. Make sure you're up to date with latest Bootstrap documentation!</p>
				</div>
				<div class="col-lg-4 col-md-4">
					<h3><i class="fa fa-pencil"></i> Ready to Style & Edit</h3>
					<p>You're ready to go with this pre-built page structure, now all you need to do is add your own custom stylings! You can see some free themes over at <a href="http://bootswatch.com">Bootswatch</a>, or come up with your own using <a href="http://getbootstrap.com/customize/">the Bootstrap customizer</a>!</p>
				</div>
				<div class="col-lg-4 col-md-4">
					<h3><i class="fa fa-folder-open"></i> Many Page Options</h3>
					<p>This template features many common pages that you might see on a business website. Pages include: about, contact, portfolio variations, blog, pricing, FAQ, 404, services, and general multi-purpose pages.</p>
				</div>
			</div>
		</div>
	</div>
	<div class="py-5 text-center">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h2>Modern Business: A Clean & Simple Full Website Template by Start Bootstrap</h2>
					<p>A complete website design featuring various single page templates from Start Bootstraps library of free HTML starter templates.</p>
					<hr>
				</div>
			</div>
		</div>
	</div>
	<div class="py-5">
		<div class="container">
			<h2 class="text-center">Featured Products</h2>
			<hr>
			<div class="row">
				{% for item in products %}
					<div class='col-md-3 col-sm-6 mb-3'>
						<div class='card'>
							<div class='card-body p-0'>
								<a href="{% url 'ecommerce:single_product' item.id %}">
									<img src='{{ item.featured_image }}' width='100%' class='img-responsive'>
								</a>
								<div class='list-group list-group-flush'>
									<div class='list-group-item border-top-0 py-2'>
										<i class='fa fa-shopping-cart fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>Price</p>
										<h4 class='list-group-item-heading'>{{ currency }} {{ item.price|intcomma }}</h4>
									</div>
									<div class='list-group-item py-2'>
										<i class='fa fa-cubes fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>On Stock</p>
										<h4 class='list-group-item-heading'>{{ item.quantity }}</h4>
									</div>
								</div>
							</div> 
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<div class="py-5">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6">
					<h2>Usto odio dignissim qui blandit praesent:</h2>
					<p></p>
					Consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum. Lorem ipsum dolor sit amet.
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6"><img src="https://picsum.photos/g/700/450/?random" class="w-100"></div>
			</div>
		</div>
	</div>
	<div class="py-5">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6"><img src="https://picsum.photos/g/700/450/?random" class="w-100"></div>
				<div class="col-lg-6 col-md-6 col-sm-6">
					<h2>Nibh euismod tincidunt ut laoreet:</h2>
					<p></p>
					Sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum. Lorem ipsum dolor sit amet. Consectetuer adipiscing elit
				</div>
			</div>
		</div>
	</div>
{% endblock %}